Repository Bapull/project_PupPatrol-react-deployment-repo, pull requests merged in 2024-09, with the labels that each got.

#58 Feature/comunity 커뮤니티 기능 추가
  public/images/Gomi.png
  public/images/Pencil.png
  public/images/Profile.png
  src/App.js
  src/components/Profile.jsx
  src/pages/Dashboard.jsx
  src/pages/Login.jsx
  src/pages/board/BoardComment.jsx
  src/pages/board/BoardCreate.jsx
  src/pages/board/BoardDescription.jsx
  src/pages/board/BoardInputForm.jsx
  src/pages/board/BoardList.jsx
  src/pages/board/BoardUpdate.jsx
  src/styles/Category_Select.css
  src/styles/Login.css
  src/styles/Profile.css
  src/styles/Register.css
  src/styles/board/BoardComment.css
  src/styles/board/BoardCreate.css
  src/styles/board/BoardDescription.css
  src/styles/board/BoardInputForm.css
  src/styles/board/BoardList.css
  src/styles/board/BoardUpdate.css
Labels: :star: Feature

#60 💡Feat :유저 프로필 사진 및 생일 추가
  src/App.js
  src/pages/Dashboard.jsx
  src/pages/Register.jsx
  src/styles/Register.css
  src/utils/fetchAPI.js
Labels: :star: Feature

#61 Bugfix/import and board create
  src/App.js
  src/pages/board/BoardCreate.jsx
  src/pages/board/BoardInputForm.jsx
  src/pages/board/BoardUpdate.jsx
Labels: :lady_beetle: BugFix

#63 💡Feat : User Update 기능 추가
  src/App.js
  src/pages/Dashboard.jsx
  src/test/UserUpdate.jsx
Labels: :star: Feature

#66 [Feature] 사용자 등록 및 조회 기능을 위한 사용자 페이지 생성
  src/App.js
  src/components/AddDog.jsx
  src/components/DogsCard.jsx
  src/pages/Login.jsx
  src/pages/User.jsx
  src/styles/AddDog.css
  src/styles/DogsCard.css
  src/styles/User.css
Labels: :star: Feature, :paintbrush: Html & Css

#68 🐛Fix : 폴더이름 잘못 입력하면 바로 에러 발생
  src/utils/fetchAPI.js
Labels: :lady_beetle: BugFix

#72 [Feature] menu component
  memo.md
  public/images/Menu.png
  src/App.js
  src/components/Menu.jsx
  src/pages/User.jsx
  src/pages/WantSelect.jsx
  src/styles/Menu.css
Labels: :+1: Enhancement, :star: Feature, :paintbrush: Html & Css
